# version: '2'

# services:
#   minio:
#     container_name: Minio
#     command: server /data --console-address ":9001"
#     environment:
#       - MINIO_ROOT_USER=admin
#       - MINIO_ROOT_PASSWORD=supersecret
#     image: quay.io/minio/minio:latest
#     ports:
#       - '9000:9000'
#       - '9001:9001'
#     volumes:
#       - ./minio:/data
#     restart: unless-stopped

#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root_pass
#       MYSQL_DATABASE: my_app_db
#       MYSQL_USER: my_app_user
#       MYSQL_PASSWORD: my_app_pass
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   # Agregar PostgreSQL
#   postgres:
#     image: postgres:13
#     container_name: postgres-mlflow
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: mlflow_db
#       POSTGRES_USER: mlflow_user
#       POSTGRES_PASSWORD: mlflow_password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   mysql_data:
#   postgres_data:  # Agregar volumen para PostgreSQL








version: '2'

services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio:/data
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: my_app_user
      MYSQL_PASSWORD: my_app_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:13
    container_name: postgres-mlflow
    restart: unless-stopped
    environment:
      POSTGRES_DB: mlflow_db
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jupyter:
    build: .
    container_name: jupyter-ml
    ports:
      - "8888:8888"
    volumes:
      - ./work:/work   # monta tu carpeta de notebooks
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=supersecret
    depends_on:
      - mysql
      - postgres
      - minio

volumes:
  mysql_data:
  postgres_data:
